export default {
  // 主题
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  SHOW_THEME_VIEW: "SHOW_THEME_VIEW",

  // 最热
  POPULAR_REFRESH: 'POPULAR_REFRESH',
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS',
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',

  // 趋势
  TRENDING_REFRESH: 'TRENDING_REFRESH',
  TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL',
  TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',
  TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS',
  TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL',

  // 收藏
  FAVORITE_LOAD_DATA: "FAVORITE_LOAD_DATA",
  FAVORITE_LOAD_SUCCESS: "FAVORITE_LOAD_SUCCESS",
  FAVORITE_LOAD_FAIL: "FAVORITE_LOAD_FAIL",

  // 语言
  LANGUAGE_LOAD_SUCCESS: "LANGUAGE_LOAD_SUCCESS",
}